language: bash
sudo: enabled

matrix:
  include:
  - name: "CUDALucas"
    before_script:
    - sed -i '/^GPU=/,/^fi/ s/^/# /' cudalucas.sh
    - sed -i '/^if ! COMPUTE=/,/^fi/ s/^/# /' cudalucas.sh
    - sed -i 's/^sed -i "s\/--generate-code/# sed -i "s\/--generate-code/' cudalucas.sh
    - sed -i 's/^\.\/CUDALucas /# .\/CUDALucas /' cudalucas.sh
    - sed -i 's/^nohup /# nohup /' cudalucas.sh
    - sed -i 's/^crontab /# crontab /' cudalucas.sh
    script:
    - ./cudalucas.sh password ANONYMOUS
  - name: "Mlucas"
    before_script:
    - sed -i 's/^nohup /# nohup /' mlucas.sh
    - sed -i 's/^crontab /# crontab /' mlucas.sh
    script:
    - ./mlucas.sh password ANONYMOUS

after_script:
    - bash -c 'shopt -s globstar; shellcheck -s bash **/*.sh || true'

